create type public.app_perimission as enum ('holy_names.delete', 'abjad.delete');
create type public.app_role as enum('master', 'student', 'user');
create type public.user_status as enum ('ONLINE', 'OFFLINE');

create table public.holy_names (
  id            bigint generated by default as identity primary key,
  holy_name          text not null unique,
  base_value int,
  submited_by    uuid references public.users not null,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
);
comment on table public.channels is 'Holy Names Collection.';

create table public.abjad (
  id            bigint generated by default as identity primary key,
  hnid    bigint references public.holy_names on delete cascade not null,
  abjad_value       int,
  calculated_by       uuid references public.users not null,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
)
comment on table public.messages is 'Abjad Values calculated by each user.';

create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references public.users on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';

-- authorize with role-based access control (RBAC)
create function public.authorize(
  requested_permission app_permission
)
returns boolean as $$
declare
  bind_permissions int;
begin
  select count(*)
  from public.role_permissions
  where role_permissions.permission = authorize.requested_permission
    and role_permissions.role = (auth.jwt() ->> 'user_role')::public.app_role
  into bind_permissions;
  
  return bind_permissions > 0;
end;
$$ language plpgsql security definer set search_path = public;
